/**
 * web3-auth-svc — EVM auth service for libpam-web3.
 *
 * Self-contained HTTPS server: serves the signing page and handles
 * auth callbacks. Port is derived from the chain name via CRC32.
 * TLS uses the certs generated by the libpam-web3 postinst.
 *
 * Routes:
 *   GET  /              — Signing page HTML
 *   GET  /engine.js     — Signing page JS
 *   GET  /auth/pending/:session_id   — Return session JSON
 *   POST /auth/callback/:session_id  — Accept signature, write .sig file
 *
 * The auth-svc does NOT verify the EVM signature — PAM's built-in ecrecover
 * handles that. This server only validates the format and writes the .sig file.
 *
 * SPECIAL profile: S7 P9 E8 C5 I7 A7 L7
 *   P9: Auth boundary — validate every input, trust nothing from the network.
 *   E8: Long-running daemon — must not crash, must not leak.
 */

import * as https from "node:https";
import * as fs from "node:fs";
import * as path from "node:path";
import { chainPort } from "./chain-port";

// ── Constants ──────────────────────────────────────────────────────────

const CHAIN_NAME = "evm";
const DEFAULT_PENDING_DIR = "/run/libpam-web3/pending";
let PENDING_DIR = DEFAULT_PENDING_DIR;
const MAX_BODY_SIZE = 256;

const SESSION_ID_RE = /^[0-9a-f]{32}$/;
// EVM signature: optional 0x prefix + 130 hex chars (65 bytes secp256k1)
const EVM_SIG_RE = /^(0x)?[0-9a-fA-F]{130}$/;


// ── Config ─────────────────────────────────────────────────────────────

const DEFAULT_CERT = "/etc/libpam-web3/tls/cert.pem";
const DEFAULT_KEY = "/etc/libpam-web3/tls/key.pem";
const DEFAULT_PAGES_DIR = "/usr/share/blockhost/signing-pages";

interface ServerConfig {
  port: number;
  pending_dir: string;
  cert: string;
  key: string;
  pages_dir: string;
}

function parseToml(content: string): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {};
  let section = "";

  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;

    const secMatch = line.match(/^\[([a-zA-Z_][a-zA-Z0-9_]*)\]$/);
    if (secMatch?.[1]) {
      section = secMatch[1];
      result[section] = result[section] || {};
      continue;
    }

    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/);
    if (!kvMatch?.[1] || !kvMatch[2] || !section) continue;

    const key = kvMatch[1];
    const val = kvMatch[2].trim();

    if (val.startsWith('"') && val.endsWith('"')) {
      result[section]![key] = val.slice(1, -1);
    } else {
      const num = Number(val);
      result[section]![key] = Number.isNaN(num) ? val : num;
    }
  }

  return result;
}

function loadConfig(configPath: string): ServerConfig {
  const defaultPort = chainPort(CHAIN_NAME);
  const defaults: ServerConfig = {
    port: defaultPort,
    pending_dir: DEFAULT_PENDING_DIR,
    cert: DEFAULT_CERT,
    key: DEFAULT_KEY,
    pages_dir: path.join(DEFAULT_PAGES_DIR, CHAIN_NAME),
  };

  let content: string;
  try {
    content = fs.readFileSync(configPath, "utf8");
  } catch {
    return defaults;
  }

  const toml = parseToml(content);
  const sec = toml["server"] || {};

  return {
    port: typeof sec.port === "number" ? sec.port : defaults.port,
    pending_dir: String(sec.pending_dir || defaults.pending_dir),
    cert: String(sec.cert || defaults.cert),
    key: String(sec.key || defaults.key),
    pages_dir: String(sec.pages_dir || defaults.pages_dir),
  };
}

// ── Validation ─────────────────────────────────────────────────────────

function isValidSessionId(id: string): boolean {
  return SESSION_ID_RE.test(id);
}

function isValidSignature(sig: string): boolean {
  return EVM_SIG_RE.test(sig);
}

// ── Route Handlers ────────────────────────────────────────────────────

function sendResponse(
  res: import("node:http").ServerResponse,
  statusCode: number,
  body: string,
  contentType = "text/plain"
): void {
  res.writeHead(statusCode, { "Content-Type": contentType });
  res.end(body);
}

function handleGetPending(sessionId: string, res: import("node:http").ServerResponse): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  let contents: string;
  try {
    contents = fs.readFileSync(jsonPath, "utf8");
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }

  sendResponse(res, 200, contents, "application/json");
}

function handlePostCallback(
  sessionId: string,
  req: import("node:http").IncomingMessage,
  res: import("node:http").ServerResponse
): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const chunks: Buffer[] = [];
  let bodySize = 0;
  let aborted = false;

  req.on("data", (chunk: Buffer) => {
    bodySize += chunk.length;
    if (bodySize > MAX_BODY_SIZE) {
      if (!aborted) {
        aborted = true;
        sendResponse(res, 413, "body too large");
        req.destroy();
      }
      return;
    }
    chunks.push(chunk);
  });

  req.on("end", () => {
    if (aborted) return;

    const body = Buffer.concat(chunks).toString("utf8").trim();

    const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
    const sigPath = path.join(PENDING_DIR, `${sessionId}.sig`);
    const tmpPath = path.join(PENDING_DIR, `${sessionId}.sig.tmp`);

    if (!fs.existsSync(jsonPath)) {
      sendResponse(res, 404, "Not Found");
      return;
    }

    if (fs.existsSync(sigPath)) {
      sendResponse(res, 409, "Conflict");
      return;
    }

    if (!isValidSignature(body)) {
      sendResponse(res, 400, "invalid signature format");
      return;
    }

    try {
      fs.writeFileSync(tmpPath, body);
      fs.renameSync(tmpPath, sigPath);
    } catch (err) {
      console.error(`Failed to write sig for session ${sessionId}: ${err}`);
      try { fs.unlinkSync(tmpPath); } catch { /* tmp may not exist */ }
      sendResponse(res, 500, "Internal Server Error");
      return;
    }

    console.log(`[AUTH] Callback signature received for session ${sessionId}`);
    sendResponse(res, 200, "OK");
  });

  req.on("error", () => { /* connection closed by client */ });
}

// ── Static file serving ───────────────────────────────────────────────

let PAGES_DIR = "";

function serveFile(
  res: import("node:http").ServerResponse,
  filePath: string,
  contentType: string
): void {
  let data: Buffer;
  try {
    data = fs.readFileSync(filePath);
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }
  res.writeHead(200, {
    "Content-Type": contentType,
    "Content-Length": data.length,
  });
  res.end(data);
}

// ── Server ────────────────────────────────────────────────────────────

function main(): void {
  const configPath = process.argv[2] || `/etc/web3-auth/${CHAIN_NAME}.toml`;
  const config = loadConfig(configPath);
  PENDING_DIR = config.pending_dir;
  PAGES_DIR = config.pages_dir;

  let tlsOpts: { cert: Buffer; key: Buffer };
  try {
    tlsOpts = {
      cert: fs.readFileSync(config.cert),
      key: fs.readFileSync(config.key),
    };
  } catch (err) {
    console.error(`[AUTH] TLS cert/key load failed: ${err}`);
    process.exit(1);
  }

  const server = https.createServer(tlsOpts, (req, res) => {
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Cache-Control", "no-store");

    const url = new URL(req.url || "/", "https://localhost");
    const pathname = url.pathname;

    // Signing page
    if (req.method === "GET" && (pathname === "/" || pathname === "/index.html")) {
      serveFile(res, path.join(PAGES_DIR, "index.html"), "text/html; charset=utf-8");
      return;
    }
    if (req.method === "GET" && pathname === "/engine.js") {
      serveFile(res, path.join(PAGES_DIR, "engine.js"), "application/javascript; charset=utf-8");
      return;
    }

    // Auth API
    const pendingMatch = pathname.match(/^\/auth\/pending\/([^/]+)$/);
    if (req.method === "GET" && pendingMatch?.[1]) {
      handleGetPending(pendingMatch[1], res);
      return;
    }

    const callbackMatch = pathname.match(/^\/auth\/callback\/([^/]+)$/);
    if (req.method === "POST" && callbackMatch?.[1]) {
      handlePostCallback(callbackMatch[1], req, res);
      return;
    }

    sendResponse(res, 404, "Not Found");
  });

  server.listen(config.port, "::", () => {
    console.log(`[AUTH] web3-auth-svc (${CHAIN_NAME}) on [::]:${config.port}`);
    console.log(`[AUTH] Pending dir: ${PENDING_DIR}`);
    console.log(`[AUTH] Pages: ${PAGES_DIR}`);
  });

  server.on("error", (err) => {
    console.error(`[AUTH] Server error: ${err}`);
    process.exit(1);
  });

  process.on("SIGTERM", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });

  process.on("SIGINT", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });
}

// Only run as a server when invoked as the entry point (auth-svc.js or
// index.ts via tsx). When imported by a test file, skip — otherwise the
// test would try to load TLS certs and bind to a port.
if (process.argv[1]?.match(/\/(auth-svc\.js|index\.ts)$/)) {
  main();
}
